package com.issam.ridem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;

// Represents an exercise entity mapped to the exercises table in the database
@Entity
@Table(name = "exercises")
@Data
public class Exercise {
    // Unique identifier for each exercise, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long exerciseId;

    // Unique name for each exercise, must start with uppercase, between 5 and 80 characters
    @NotBlank
    @Size(min=5, max=80)
    @Pattern(regexp="^[A-Z].*")
    private String name;

    // Muscle group to which belongs the exercise, must start with uppercase, between 3 and 10 characters
    @NotBlank
    @Size(min=3, max=10)
    @Pattern(regexp="^[A-Z].*")
    private String muscleGroup;
    
    // Equipment required to perform the exercise, optional
    private String equipment;

    // Short description of how to perform the exercise, optional
    private String description; 
}
