package com.issam.ridem.entity;

import jakarta.persistence.*;
import lombok.Data;

// Represents an exercise entity mapped to the exercises table in the database
@Entity
@Table(name = "exercises")
@Data
public class Exercise {
    // Unique identifier for each exercise, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long exerciseId;

    // Unique name for each exercise
    @Column(unique = true)
    private String name;

    // Muscle group to which belongs the exercise
    private String muscleGroup;
    
    // Equipment required to perform the exercise, optional
    private String equipment;

    // Short description of how to perform the exercise, optional
    private String description; 
}
