package com.issam.ridem.entity;

import jakarta.persistence.*;
import lombok.Data;

// Represents a set entity mapped to the sets table in the database
@Entity
@Table(name = "sets")
@Data
public class Set {
    
    // Unique identifier for each set, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long setId;

    // Session exercises this set belongs to, foreign key (session_exercise_id)
    @ManyToOne
    @JoinColumn(name = "session_exercise_id")
    private SessionExercise sessionExercise;

    // Performed number of repetitions per set
    private Integer reps;

    // Performed weight for the set in kg
    private Double weight;
}
