package com.issam.ridem.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

// Represents a user entity mapped to the users table in the database.
@Entity
@Table(name = "users")
@Data
public class User {
    // Unique identifier for each user, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;

    // Unique name for each user
    private String name;
    // Unique email as alternative identifier and for account recovery
    private String email;
    // Password for authentication stored as hash
    private String password;
    // Age of the user, optional since it is not required to use the app
    private Integer age;
}
