package com.issam.ridem.entity;

import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.persistence.*;
import lombok.Data;

// Workout session linked to a User and a WorkoutTemplate, stored in the workout_sessions table 
@Entity
@Table(name = "workout_sessions")
@Data
public class WorkoutSession {
    
    // Unique identifier for each session, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long sessionId;

    // Owner of this session, referenced as a foreign key (user_id) in the database 
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;
    
    // Template of this session, referenced as a foreign key (template_id) in the database 
    @ManyToOne
    @JoinColumn(name = "template_id")
    private WorkoutTemplate workoutTemplate;
    
    // Date the session was performed, defaults to today if not provided
    @JsonFormat(pattern = "dd.MM.yyyy")
    private LocalDate date;

    // Optional notes to allow the user to add remarks about the session
    private String notes;
}
