package com.issam.ridem.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;

// Workout template owned by a user, mapped to the workout_templates table
@Entity
@Table(name = "workout_templates")
@Data
public class WorkoutTemplate {
    // Unique identifier for each template, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long templateId;

    // Template name, must start with uppercase, between 3 and 30 characters
    @NotBlank
    @Size(min=3, max=30)
    @Pattern(regexp="^[A-Z].*")
    private String name;

    // Owner of this template, referenced as a foreign key (user_id) in the database 
    @NotNull
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;
    
}