package com.issam.ridem.entity;

import jakarta.persistence.*;
import lombok.Data;

// Workout template owned by a user, mapped to the workout_templates table
@Entity
@Table(name = "workout_templates")
@Data
public class WorkoutTemplate {
    // Unique identifier for each template, auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long templateId;

    // Name of the template
    private String name;

    // Owner of this template, referenced as a foreign key (user_id) in the database
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;
}